### ISSUE TITLE
Webinterface Error: Failed to lookup view "status"

### ISSUE THREAD

**Issue by sekuba** [n-thumann/IPTV-ReStream#238]
Hi. I happily used your nodejs package until i tried to change to a docker container today.
When trying to open the webinterface i get 
```
Error: Failed to lookup view "status" in views directory "/views"
    at Function.render (/app/node_modules/express/lib/application.js:597:17)
    at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
    at /app/routes/status.js:11:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
```
The log shows the same:
```
IPTV-ReStream  | 2023-11-13T12:59:54.711Z iptv-restream:config Config loaded: HOST=127.0.0.1, PORT=3000, MCAST_IF=0.0.0.0, XSPF_PROTOCOL=https, XSPF_HOST=my.server.com:8080, XSPF_PATH_PREFIX=/iptv, ALLOW_UNKNOWN=false
IPTV-ReStream  | 2023-11-13T12:59:54.724Z iptv-restream:server Listening on port 127.0.0.1:3000...
IPTV-ReStream  | 2023-11-13T12:59:54.725Z iptv-restream:station Stations loaded
IPTV-ReStream  | 127.0.0.1 - - [13/Nov/2023:12:59:57 +0000] "GET / HTTP/1.1" 302 56 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"
IPTV-ReStream  | 127.0.0.1 - - [13/Nov/2023:12:59:57 +0000] "GET /status HTTP/1.1" 500 1075 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"
IPTV-ReStream  | Error: Failed to lookup view "status" in views directory "/views"
IPTV-ReStream  |     at Function.render (/app/node_modules/express/lib/application.js:597:17)
IPTV-ReStream  |     at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
IPTV-ReStream  |     at /app/routes/status.js:11:9
IPTV-ReStream  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
IPTV-ReStream  |     at next (/app/node_modules/express/lib/router/route.js:144:13)
IPTV-ReStream  |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
IPTV-ReStream  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
IPTV-ReStream  |     at /app/node_modules/express/lib/router/index.js:284:15
IPTV-ReStream  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
IPTV-ReStream  |     at next (/app/node_modules/express/lib/router/index.js:280:10)
```

I reproduced this on Ubuntu and WSL(Ubuntu) separately by cloning your repo and runnig the provided docker-compose.example.yml

**Comment by n-thumann** [comment]
Whoops, I must have missed testing the Docker image 😬
Fixed via https://github.com/n-thumann/IPTV-ReStream/pull/239

**Comment by n-thumann** [comment]
Release https://github.com/n-thumann/IPTV-ReStream/releases/tag/v1.5.0 contains the corresponding fix ✌🏻

**Comment by sekuba** [comment]
works, thank you :)
