### ISSUE TITLE
IPTV-ReStream gets killed when MCAST_IF is set

### ISSUE THREAD

**Issue by ostpol** [n-thumann/IPTV-ReStream#91]
Because of my setup I need to set MCAST_IF and HOST. When I try to open any stream in VLC, IPTV-ReStream gets killed:

```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@7.3.0
2 info using node@v15.5.1
3 timing config:load:defaults Completed in 8ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 9ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/tony/downloads/IPTV-ReStream/.npmrc Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/tony/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 2ms
17 timing config:load:setEnvs Completed in 5ms
18 timing config:load Completed in 35ms
19 verbose npm-session 4f6c283d4d5c11b0
20 timing npm:load Completed in 74ms
21 timing command:run-script Completed in 10364ms
22 timing command:start Completed in 10375ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (node:events:376:20)
23 verbose stack     at maybeClose (node:internal/child_process:1063:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
24 verbose pkgid iptv-restream@1.2.0
25 verbose cwd /home/tony/downloads/IPTV-ReStream
26 verbose Linux 5.4.0-58-generic
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
28 verbose node v15.5.1
29 verbose npm  v7.3.0
30 error code 1
31 error path /home/tony/downloads/IPTV-ReStream
32 error command failed
33 error command sh -c node dist/app.js
34 verbose exit 1
```

When MCAST_IF isn't set and I try to start any stream, IPTV-ReStream keeps running (but the stream doesn't start). Any ideas? What further informations can I look for to get into this?

When started as a service, journalctl tells me:

```
Jan 05 20:23:42 tvpc npm[8387]: node:dgram:872
Jan 05 20:23:42 tvpc npm[8387]:     throw errnoException(err, 'addSourceSpecificMembership');
Jan 05 20:23:42 tvpc npm[8387]:     ^
Jan 05 20:23:42 tvpc npm[8387]: Error: addSourceSpecificMembership EINVAL
Jan 05 20:23:42 tvpc npm[8387]:     at Socket.addSourceSpecificMembership (node:dgram:872:11)
Jan 05 20:23:42 tvpc npm[8387]:     at Socket.<anonymous> (/home/tony/downloads/IPTV-ReStream/dist/providers/stream.js:29:26)
Jan 05 20:23:42 tvpc npm[8387]:     at Socket.emit (node:events:376:20)
Jan 05 20:23:42 tvpc npm[8387]:     at startListening (node:dgram:153:10)
Jan 05 20:23:42 tvpc npm[8387]:     at node:dgram:348:7
Jan 05 20:23:42 tvpc npm[8387]:     at processTicksAndRejections (node:internal/process/task_queues:81:21) {
Jan 05 20:23:42 tvpc npm[8387]:   errno: -22,
Jan 05 20:23:42 tvpc npm[8387]:   code: 'EINVAL',
Jan 05 20:23:42 tvpc npm[8387]:   syscall: 'addSourceSpecificMembership'
Jan 05 20:23:42 tvpc npm[8387]: }
Jan 05 20:23:42 tvpc npm[8361]: npm ERR! code 1
Jan 05 20:23:42 tvpc npm[8361]: npm ERR! path /home/tony/downloads/IPTV-ReStream
Jan 05 20:23:42 tvpc npm[8361]: npm ERR! command failed
Jan 05 20:23:42 tvpc npm[8361]: npm ERR! command sh -c node dist/app.js
Jan 05 20:23:42 tvpc systemd[1]: restream.service: Main process exited, code=exited, status=1/FAILURE
Jan 05 20:23:42 tvpc systemd[1]: restream.service: Failed with result 'exit-code'.
Jan 05 20:23:42 tvpc systemd[1]: restream.service: Scheduled restart job, restart counter is at 1.
Jan 05 20:23:42 tvpc systemd[1]: Stopped IPTV-ReStream.
```

**Comment by n-thumann** [comment]
Sounds like an invalid `MCAST_IF` address. Can you run IPTV-ReStream with environment variable `DEBUG=iptv-restream:*` set again and post the full log? What value do you have `MCAST_IF` set to? 😊

**Comment by ostpol** [comment]
It's allways sad, when the solutions is... reading. :expressionless:

I've set `MCAST_IF` to the interfaces name and not it's address (as it was possible for udpxy). "joins the multicast group using this interface (default `0.0.0.0`, lets OS choose automatically)" should've been the hint.

Thank you!
